### ISSUE TITLE
update docusaurus to 4.0+

### ISSUE THREAD

**Issue by BluRosie** [ds-pokemon-hacking/ds-pokemon-hacking.github.io#50]
should resolve the error we are getting on deploy per https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/911

should just be changing [`package.json`](https://github.com/ds-pokemon-hacking/ds-pokemon-hacking.github.io/blob/main/package.json)?

**Comment by PlatinumMaster** [comment]
Solved by #51.
